### ISSUE TITLE
Hello, I just begin studying about  OCR-correction. Could you tell me how to use natas with a pretrained-model?

### ISSUE THREAD

**Issue by trongvanhpkt99** [mikahama/natas#2]

**Comment by trongvanhpkt99** [comment]
I want to train a model for OCR-correcting output in Vietnamese, so at fist I want to know how to use a pre-trained model

**Comment by mikahama** [comment]
We only have a pretrained model for English at the moment, so it will not work with Vietnamese. Natas calls [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) on the background, so basically you can use `onmt_translate ` with your own model, pass it -n_best 10 and filter the results with a dictionary.

**Comment by trongvanhpkt99** [comment]
> We only have a pretrained model for English at the moment, so it will not work with Vietnamese. Natas calls [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) on the background, so basically you can use `onmt_translate ` with your own model, pass it -n_best 10 and filter the results with a dictionary.

Thank you! Can you give me the English pretrained model and tell me how to use it?

**Comment by mikahama** [comment]
This is how to use it from Natas:
```
import natas
natas.ocr_correct_words(["paft", "friendlhip"])
```
To use it with OpenNMT, you must first [download the model](https://github.com/mikahama/natas/blob/master/natas/models/ocr.pt). 

Then you will need to prepare a text file with the words you want to OCR post-correct so that there is one word per line and each word should be split into characters.

So if you have a sentence _cat ran avvay_ you should produce the following text file _ocr_errors.txt_

```
c a t
r a n
a v v a y
```
Then you can run `onmt_translate -model ocr.pt -src ocr_errors.txt -output ocr_fixed.txt -replace_unk -verbose`. This will produce a text file _ocr_fixed.txt_ with the OCR corrections. OpenNMT lets you do all sorts of things in translate, so please refer to [their documentation](https://opennmt.net/OpenNMT-py/options/translate.html) as well.

**Comment by trongvanhpkt99** [comment]
> This is how to use it from Natas:
> 
> ```
> import natas
> natas.ocr_correct_words(["paft", "friendlhip"])
> ```
> 
> To use it with OpenNMT, you must first [download the model](https://github.com/mikahama/natas/blob/master/natas/models/ocr.pt).
> 
> Then you will need to prepare a text file with the words you want to OCR post-correct so that there is one word per line and each word should be split into characters.
> 
> So if you have a sentence _cat ran avvay_ you should produce the following text file _ocr_errors.txt_
> 
> ```
> c a t
> r a n
> a v v a y
> ```
> 
> Then you can run `onmt_translate -model ocr.pt -src ocr_errors.txt -output ocr_fixed.txt -replace_unk -verbose`. This will produce a text file _ocr_fixed.txt_ with the OCR corrections. OpenNMT lets you do all sorts of things in translate, so please refer to [their documentation](https://opennmt.net/OpenNMT-py/options/translate.html) as well.

Thank you! I'll try it
